language: android

android:
  components:
    - tools
    - build-tools-26.1.1
    - android-26
    - platform-tools
    - add-on
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - yes | sdkmanager "platforms;android-27"
script:
  - ./gradlew build connectedCheck
