language: android
before_cache:
  -rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  -rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    -$HOME/.gradle/caches/
    -$HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
env:
  global:
    - ANDROID_API=26
    - ANDROID_BUILD_TOOLS=26.1.1
    - ANDROID_EMU_API_LEVEL=22
    - ANDROID_ABI=armeabi-v7a
    - ADB_INSTALL_TIMEOUT=5 # minutes
android:
  components:
    - tools
    - build-tools-26.1.1
    - android-26
    - platform-tools
    - add-on
    - extra-android-m2repository
    - extra-google-m2repository
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$ANDROID_EMU_API_LEVEL
    - extra-android-support
    - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMU_API_LEVEL
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
  - yes | sdkmanager "platforms;android-27"
script:
  - ./gradlew test
